name: endvpn
description: End VPN - Premium VPN client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^10.1.2
  crypto: ^3.0.3
  logger: ^2.4.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_singbox_vpn: ^1.1.2
  shared_preferences: ^2.3.2
  app_links: ^6.3.4
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700