[Version]
Class=IEXPRESS
SEDVersion=3

[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=EndVPN installed successfully.
TargetName=C:\Projects\bot_vpn\endvpn\build\release_artifacts\EndVPNSetup-new.exe
FriendlyName=EndVPN Setup
AppLaunched=install.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles

[Strings]
FILE0=install.cmd
FILE1=install.ps1
FILE2=EndVPN-windows-release.zip

[SourceFiles]
SourceFiles0=C:\Projects\bot_vpn\endvpn\installer\windows\

[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=

