import 'dart:async';
import 'flutter_singbox_platform_interface.dart';

/// Main class for the Flutter SingBox VPN plugin.
class FlutterSingbox {
  /// Get platform version
  Future<String?> getPlatformVersion() {
    return FlutterSingboxPlatform.instance.getPlatformVersion();
  }

  /// Save SingBox configuration
  ///
  /// [config] is a JSON string containing the SingBox configuration
  Future<bool> saveConfig(String config) {
    return FlutterSingboxPlatform.instance.saveConfig(config);
  }

  /// Get current SingBox configuration
  Future<String> getConfig() {
    return FlutterSingboxPlatform.instance.getConfig();
  }

  /// Start VPN connection
  Future<bool> startVPN() {
    return FlutterSingboxPlatform.instance.startVPN();
  }

  /// Stop VPN connection
  Future<bool> stopVPN() {
    return FlutterSingboxPlatform.instance.stopVPN();
  }

  /// Get current VPN status
  ///
  /// Returns one of the following strings:
  /// - "Stopped"
  /// - "Starting"
  /// - "Started"
  /// - "Stopping"
  Future<String> getVPNStatus() {
    return FlutterSingboxPlatform.instance.getVPNStatus();
  }

  /// Stream of VPN status updates
  ///
  /// Emits a map with the following keys:
  /// - "status": String (Stopped, Starting, Started, Stopping)
  /// - "statusCode": int (0=Stopped, 1=Starting, 2=Started, 3=Stopping)
  Stream<Map<String, dynamic>> get onStatusChanged {
    return FlutterSingboxPlatform.instance.onStatusChanged;
  }

  /// Stream of traffic statistics updates
  ///
  /// Emits a map with the following keys:
  /// - "uplinkSpeed": long (bytes per second)
  /// - "downlinkSpeed": long (bytes per second)
  /// - "uplinkTotal": long (total bytes sent)
  /// - "downlinkTotal": long (total bytes received)
  /// - "connectionsIn": int (number of inbound connections)
  /// - "connectionsOut": int (number of outbound connections)
  /// - "sessionUplink": long (bytes sent in current session)
  /// - "sessionDownlink": long (bytes received in current session)
  /// - "sessionTotal": long (total bytes in current session)
  /// - "formattedUplinkSpeed": String (human readable, e.g. "1.24 KB/s")
  /// - "formattedDownlinkSpeed": String (human readable)
  /// - "formattedUplinkTotal": String (human readable)
  /// - "formattedDownlinkTotal": String (human readable)
  /// - "formattedSessionUplink": String (human readable)
  /// - "formattedSessionDownlink": String (human readable)
  /// - "formattedSessionTotal": String (human readable)
  Stream<Map<String, dynamic>> get onTrafficUpdate {
    return FlutterSingboxPlatform.instance.onTrafficUpdate;
  }

  /// Set per-app tunneling mode
  ///
  /// Valid values:
  /// - "off" - Tunnel all applications
  /// - "include" - Only tunnel specified apps
  /// - "exclude" - Tunnel all apps except those specified
  Future<bool> setPerAppProxyMode(String mode) {
    return FlutterSingboxPlatform.instance.setPerAppProxyMode(mode);
  }

  /// Get current per-app tunneling mode
  Future<String> getPerAppProxyMode() {
    return FlutterSingboxPlatform.instance.getPerAppProxyMode();
  }

  /// Set list of apps for per-app tunneling
  ///
  /// [appList] should be a list of package names
  Future<bool> setPerAppProxyList(List<String>? appList) {
    return FlutterSingboxPlatform.instance.setPerAppProxyList(appList);
  }

  /// Get current list of apps for per-app tunneling
  Future<List<String>> getPerAppProxyList() {
    return FlutterSingboxPlatform.instance.getPerAppProxyList();
  }

  /// Get list of installed apps
  ///
  /// Returns a list of maps with these keys:
  /// - "packageName": String (package name of the app)
  /// - "appName": String (display name of the app)
  /// - "isSystemApp": bool (true if the app is a system app)
  Future<List<Map<String, dynamic>>> getInstalledApps() {
    return FlutterSingboxPlatform.instance.getInstalledApps();
  }

  /// Stream of log messages from the VPN service
  ///
  /// Emits log messages as they are generated by the sing-box core.
  /// Each event is a map with:
  /// - "type": String ("log" or "clear")
  /// - "message": String (the log message, only present when type is "log")
  Stream<Map<String, dynamic>> get onLogMessage {
    return FlutterSingboxPlatform.instance.onLogMessage;
  }

  /// Get buffered log messages
  ///
  /// Returns a list of recent log messages that have been buffered.
  Future<List<String>> getLogs() {
    return FlutterSingboxPlatform.instance.getLogs();
  }

  /// Clear the log buffer
  Future<bool> clearLogs() {
    return FlutterSingboxPlatform.instance.clearLogs();
  }

  /// Set notification title
  ///
  /// [title] is the title to show in the VPN service notification.
  /// For example: "SafePro VPN" or "My VPN App"
  /// This should be called before starting the VPN.
  Future<bool> setNotificationTitle(String title) {
    return FlutterSingboxPlatform.instance.setNotificationTitle(title);
  }

  /// Get notification title
  Future<String> getNotificationTitle() {
    return FlutterSingboxPlatform.instance.getNotificationTitle();
  }

  /// Set notification description
  ///
  /// [description] is the description/content text to show in the notification.
  /// For example: "Connected" or "VPN is active"
  /// This should be called before starting the VPN.
  Future<bool> setNotificationDescription(String description) {
    return FlutterSingboxPlatform.instance.setNotificationDescription(
      description,
    );
  }

  /// Get notification description
  Future<String> getNotificationDescription() {
    return FlutterSingboxPlatform.instance.getNotificationDescription();
  }
}

/// Helper class for VPN Status
class VPNStatus {
  static const String STOPPED = "Stopped";
  static const String STARTING = "Starting";
  static const String STARTED = "Started";
  static const String STOPPING = "Stopping";
}

/// Helper class for Per-App Tunneling Modes
class ProxyMode {
  static const String OFF = "off";
  static const String INCLUDE = "include";
  static const String EXCLUDE = "exclude";
}
